name: Build and Deploy

on:
  push:
    branches:
      - main  # Change to the branch you want to build from

permissions:
  contents: write

jobs:
  build:
    name: Build and Deploy to Dist Branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: yarn install

    - name: Build Project
      run: yarn build

    - name: Debug Build Output
      run: ls -la dist

    - name: Prepare Dist Directory
      run: |
        # Create a temporary directory to store build files
        mkdir -p temp_dist
        # Copy build files to the temporary directory
        cp -r dist/* temp_dist
        # Debug: List the contents of temp_dist
        ls -la temp_dist

    - name: Deploy to dist Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git fetch origin
        git checkout -B dist
        # Delete node_modules directory
        rm -rf node_modules
        # Delete all files except .git and .github directories
        find . -not -name '.git*' -not -path './.github*' -delete
        # Debug: Ensure the temp_dist directory exists before copying
        ls -la temp_dist
        # Copy build files from the temporary directory to the root
        cp -r temp_dist/* .
        # Remove the temporary directory
        rm -rf temp_dist
        git add .
        git commit -m "Deploy to dist branch"
        git push origin dist --force
